### ISSUE TITLE
[GIT] 로컬 master 에서 작업을 시작해버렸어요! 어떻게 하면 좋죠 ㅠ_ㅠ

### ISSUE THREAD

**Issue by kim4pb** [datarian-kr/datarian-kr.github.io#55]

**Comment by ysunmi0427** [comment]
작업용 branch 를 따로 만들어서 push 하자는 팀 내 컨벤션이 있음에도 우리는 종종 로컬 master branch 에서 작업을 시작해버린다. 이 때 어떻게 대처해야하는지를 가이드하기 위한 문서이며, 초보 깃 사용자들에게 자주 사용하는 git command 를 쉽게 소개한다.
